apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: webapp-color
spec:
  maxReplicas: 6
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webapp-color
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 100
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 15
      policies:
      - type: Pods
        value: 1
        periodSeconds: 10